version: "3"
services:
  pets:
    build: "./pets"
    image: "pet-store-pets-service:latest"
    volumes:
      - ./pets/data.json:/usr/src/app/data.json
    environment:
      - NODE_ENV=production

  owners:
    build: "./owners"
    image: "pet-store-owners-service:latest"
    volumes:
      - ./owners/data.json:/usr/src/app/data.json
    environment:
      - NODE_ENV=production
    depends_on:
      - pets

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./web/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - pets
      - owners
